# camera0: "http://10.51.1.62:8080/shot.jpg"
# camera1: "http://192.168.137.104:8080/shot.jpg"
# frame_width: 1280
# frame_height: 720
# mono_calibration_frames: 10
# stereo_calibration_frames: 10
# view_resize: 2 # 1
# checkerboard_box_size_scale : 2.19
# checkerboard_rows: 6
# checkerboard_columns: 9
# cooldown: 1

camera0: 4
camera1: 6
frame_width: 1280
frame_height: 720
mono_calibration_frames: 10
stereo_calibration_frames: 10
view_resize: 1
checkerboard_box_size_scale : 3.19
checkerboard_rows: 4
checkerboard_columns: 7
cooldown: 100