camera0: "http://192.168.137.22:8080/shot.jpg"
camera1: "http://192.168.137.104:8080/shot.jpg"
frame_width: 1280
frame_height: 720
mono_calibration_frames: 10
stereo_calibration_frames: 10
view_resize: 2 # 1
checkerboard_box_size_scale : 2.19
checkerboard_rows: 6
checkerboard_columns: 9
cooldown: 5